### ISSUE TITLE
search buffer

### ISSUE THREAD

**Issue by cj** [mitsuhiko/dotfiles#2]
Hi,

I was wondering how you are showing the search results in a buffer when searching something via '/' (https://db.tt/EFdmeQwc)?

**Comment by bnjmn** [comment]
I was wondering this myself and came up with what I think is being represented here:
- Use [ack.vim](https://github.com/mileszs/ack.vim) and run `:Ack flask.request` to get the search buffer
- `:set hlsearch` will highlight all match to previous search pattern
- it makes the most sense that the `/flask.request` search has already been entered and is just re-typed here to show context
