### ISSUE TITLE
Issue with setting up zsh theme

### ISSUE THREAD

**Issue by kshitij10496** [mitsuhiko/dotfiles#4]
Hey @mitsuhiko 

I am facing some problem in setting your `zsh` theme on my terminal.
There seems to be some issue with `precmd_update_git_vars` command.
Here is the an instance :

```
kshitij10496 at Kshitijs-MacBook-Pro in ~
$ async_prompt:2: command not found: precmd_update_git_vars

kshitij10496 at Kshitijs-MacBook-Pro in ~
$ ls
Blog      Documents Library   Music     Public
Desktop   Downloads Movies    Pictures  Software

kshitij10496 at Kshitijs-MacBook-Pro in ~
$ async_prompt:2: command not found: precmd_update_git_vars

kshitij10496 at Kshitijs-MacBook-Pro in ~
$
```
I know you must be really busy but I would appreciate if you can help me with fixing this.
Thanks for sharing your dot files and all the wonderful projects. :)

**Comment by mitsuhiko** [comment]
I don't know enough about zsh to understand what this does. All I know is that it works on the base of my zsh.
